### ISSUE TITLE
Problemas com nome da função no Windows

### ISSUE THREAD

**Issue by lucaskaiut** [rodrigorgtic/rcomponent#1]
Ao criar um componente com o rnbc, o nome do componente ficou com o caminho completo do arquivo, no meu caso: "C:\development\NLWWidgetMobile\src\components\Widget". 

Obviamente eu só preciso apagar a parte indesejada, mas seria legal se criasse com o nome correto.

![image](https://user-images.githubusercontent.com/24759223/168114011-0e332636-771f-4a78-b38c-bc1281257980.png)

**Comment by orodrigogo** [comment]
Olá lucaskaiut, 

Você poderia me dizer qual é a versão do seu windows?

Muito obrigado pelo seu feedback!

**Comment by orodrigogo** [comment]
Testing and work.
